(()=>{
  const C=window.__GFM,V=window.GFMV4;if(!C||!V)return;
  const {S,esc,brl,today,num,by,pname,toast,api,render,mutate,optionCards}=C,H=V.helpers,G=window.G;
  const cardCfg=c=>H.cardSettings(c),month=()=>H.monthKey(S.cardMonth||today().slice(0,7));
  const cardItems=(c,m)=>S.cardSchedule.filter(i=>i.credit_card_id===c.id&&H.monthKey(i.competency_date)===m);
  const gross=(c,m)=>cardItems(c,m).reduce((s,i)=>s+Number(i.amount||0),0);
  const reimb=(c,m)=>cardItems(c,m).reduce((s,i)=>s+Number(i.reimbursement_expected||0),0);
  const paid=(c,m)=>S.tx.filter(t=>t.type==='card_payment'&&t.status==='paid'&&(H.noteHas(t,H.tag('cardpay',c.id,m))||(H.monthKey(H.txdate(t))===m&&String(t.description||'').includes(c.name)))).reduce((s,t)=>s+H.amount(t),0);
  const plan=(c,m)=>S.household?.settings?.card_plans?.[`${c.id}:${m}`]||null;
  const open=(c,m)=>plan(c,m)?0:Math.max(0,gross(c,m)-paid(c,m));
  const dueDate=(c,m)=>`${m}-${String(Math.max(1,Math.min(28,Number(cardCfg(c).due_day||10)))).padStart(2,'0')}`;
  const inferredDue=(c,purchase)=>{const cfg=cardCfg(c),close=Math.max(1,Math.min(28,Number(cfg.closing_day||1))),due=Math.max(1,Math.min(28,Number(cfg.due_day||10))),d=new Date(purchase+'T12:00:00');let y=d.getFullYear(),mo=d.getMonth();if(d.getDate()>=close)mo++;if(due<=close)mo++;return new Date(y,mo,due,12).toISOString().slice(0,10)};
  async function clearOpen(c,m){const marker=H.tag('cardopen',c.id,m);for(const t of S.tx.filter(x=>x.status==='pending'&&H.noteHas(x,marker)))await api(`/rest/v1/transactions?id=eq.${encodeURIComponent(t.id)}`,{method:'PATCH',body:{deleted_at:new Date().toISOString()}})}
  async function createOpen(c,m,value,date){if(!(value>0))return;const pid=H.cardOwner(c),acct=H.primaryAccount(pid);if(!acct)return;await H.insertTx({household_id:S.hid,type:'card_payment',status:'pending',description:`Fatura ${c.name} — saldo em aberto`,responsible_person_id:pid,account_id:acct.id,competency_date:date,due_date:date,planned_amount:value,actual_amount:null,notes:`${H.tag('cardopen',c.id,m)} Saldo restante`,origin:'manual',created_by:S.session.user.id})}
  async function createCardReimb(c,description,value,date){if(!(value>0))return;const pid=H.cardOwner(c),acct=H.primaryAccount(pid);if(!acct)return;const cat=S.categories.find(x=>String(x.name||'').toLowerCase()==='reembolso');await H.insertTx({household_id:S.hid,type:'income',status:'pending',description:`Reembolso — ${description}`,category_id:cat?.id||null,responsible_person_id:pid,account_id:acct.id,competency_date:date,due_date:date,planned_amount:value,actual_amount:null,notes:`Reembolso automático de compra no ${c.name}`,origin:'manual',created_by:S.session.user.id})}
  V.cards=()=>{
    const months=[...new Set(S.cardSchedule.map(x=>H.monthKey(x.competency_date)).filter(Boolean))].sort();if(!S.cardMonth)S.cardMonth=months.includes(today().slice(0,7))?today().slice(0,7):(months[0]||today().slice(0,7));const m=month(),base=S.cardSchedule.filter(i=>H.monthKey(i.competency_date)===m),items=S.cardFilter?base.filter(i=>i.credit_card_id===S.cardFilter):base;
    return `<div class="actions cardactions"><button class="btn primary" onclick="G.modal('purchase')">＋ Despesa cartão</button><select class="btn" onchange="G.cardMonth(this.value)">${months.map(x=>`<option value="${x}" ${x===m?'selected':''}>${H.monthLabel(x)}</option>`).join('')}</select><button class="btn ${!S.cardFilter?'primary':''}" onclick="G.cardFilter(null)">Todos</button></div><div class="grid cardsgrid">${S.cards.map(c=>{const cfg=cardCfg(c),g=gross(c,m),r=reimb(c,m),p=paid(c,m),o=open(c,m),pl=plan(c,m);return `<article class="cardbox clickable ${S.cardFilter===c.id?'selected':''}" onclick="G.cardFilter('${c.id}')"><div><div class="cardtop"><div><div class="muted small">${esc(c.institution||'Cartão')}</div><h3>${esc(c.name)}</h3></div><button class="cardedit" onclick="event.stopPropagation();G.modal('cardsettings',null,'${c.id}')">⚙</button></div><div class="muted small">${cfg.limit?`Limite ${brl(cfg.limit)} · fecha dia ${cfg.closing_day||'—'} · vence dia ${cfg.due_day||'—'}`:'Configure limite, fechamento e vencimento'}</div></div><div><div class="muted small">Fatura ${pl?'parcelada':'projetada'}</div><div class="cardvalue">${brl(g)}</div><div class="muted small">Pago ${brl(p)} · em aberto ${brl(o)} · reembolso ${brl(r)} · líquido ${brl(g-r)}</div></div><div class="cardbuttons">${pl?`<span class="planbadge">${pl.entry>0?`entrada ${brl(pl.entry)} + `:''}${pl.installments}x ${brl(pl.installment_amount)}</span>`:`<button class="btn inv" onclick="event.stopPropagation();G.modal('cardpay',null,'${c.id}')">Pagar fatura</button><button class="btn inv" onclick="event.stopPropagation();G.modal('cardplan',null,'${c.id}')">Parcelar fatura</button>`}</div></article>`}).join('')}</div><div class="space"></div><section class="panel"><div class="panelhead"><h2>Itens da fatura${S.cardFilter?' · '+esc(by(S.cards,S.cardFilter)?.name||''):''}</h2><span class="small muted">${items.length} item(ns)</span></div>${items.length?`<div class="tablewrap"><table class="table"><thead><tr><th>Cartão</th><th>Item</th><th>Parcela</th><th>Valor</th><th>Reembolso</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(by(S.cards,i.credit_card_id)?.name||'Cartão')}</td><td><b>${esc(i.item)}</b><div class="muted small">${esc(i.item_type||'')}</div></td><td>${esc(i.installment_label||'—')}</td><td>${brl(i.amount)}</td><td>${Number(i.reimbursement_expected||0)>0?`${brl(i.reimbursement_expected)} · ${esc(i.reimburser||'')}`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Sem itens neste mês/cartão.</div>'}</section>`
  };
  V.modalHandlers.purchase=()=>{const c=S.cards[0],d=c?inferredDue(c,today()):today();return `<div class="modalback" onclick="if(event.target===this)G.close()"><div class="modal"><div class="modalhead"><h2>Despesa cartão</h2><button class="close" onclick="G.close()">×</button></div><form onsubmit="G.submitPurchaseV4(event)" class="formgrid"><div class="field full"><label>Descrição</label><input name="description" required autofocus></div><div class="field"><label>Cartão</label><select name="card" onchange="G.cardPurchaseChanged(this.value)">${optionCards()}</select><div id="purchaseOwner" class="ownerhint">Responsável: ${c?pname(H.cardOwner(c)):'—'}</div></div><div class="field"><label>Valor total</label><input name="amount" inputmode="decimal" required></div><div class="field"><label>Data da compra</label><input id="purchaseDate" name="date" type="date" value="${today()}" onchange="G.cardPurchaseChanged(document.querySelector('[name=card]').value)" required></div><div class="field"><label>Parcelas</label><input name="count" type="number" min="1" max="60" value="1"></div><div class="field"><label>1º vencimento</label><input id="purchaseDue" name="first" type="date" value="${d}" required></div>${H.categoryFields('purchase')}<div class="field"><label>Tem reembolso?</label><select name="has_reimb" onchange="G.reimbChanged(this.value,'cardReimbExtra')"><option value="no">Não</option><option value="yes">Sim</option></select></div><div id="cardReimbExtra" class="field hidden"><label>Valor do reembolso</label><input name="reimb_amount" inputmode="decimal"></div><div class="field full"><label>Observação</label><textarea name="notes"></textarea></div><div class="field full formactions"><button class="btn" type="button" onclick="G.close()">Cancelar</button><button class="btn primary">Salvar</button></div></form></div></div>`};
  V.modalHandlers.cardsettings=()=>{const c=by(S.cards,S.modal.id);if(!c)return'';const cfg=cardCfg(c);return `<div class="modalback" onclick="if(event.target===this)G.close()"><div class="modal compact"><div class="modalhead"><h2>${esc(c.name)}</h2><button class="close" onclick="G.close()">×</button></div><form onsubmit="G.saveCardSettings(event,'${c.id}')" class="formgrid"><div class="field full"><label>Limite do cartão</label><input name="limit" inputmode="decimal" value="${cfg.limit?String(cfg.limit).replace('.',','):''}"></div><div class="field"><label>Dia de fechamento</label><input name="closing" type="number" min="1" max="28" value="${cfg.closing_day||1}"></div><div class="field"><label>Dia de vencimento</label><input name="due" type="number" min="1" max="28" value="${cfg.due_day||10}"></div><div class="field full formactions"><button class="btn" type="button" onclick="G.close()">Cancelar</button><button class="btn primary">Salvar cartão</button></div></form></div></div>`};
  V.modalHandlers.cardpay=()=>{const c=by(S.cards,S.modal.id);if(!c)return'';const m=month(),g=gross(c,m),p=paid(c,m),o=open(c,m);return `<div class="modalback" onclick="if(event.target===this)G.close()"><div class="modal compact"><div class="modalhead"><h2>Pagar fatura · ${esc(c.name)}</h2><button class="close" onclick="G.close()">×</button></div><div class="invoicebrief"><div><span>Fatura</span><b>${brl(g)}</b></div><div><span>Já pago</span><b>${brl(p)}</b></div><div><span>Em aberto</span><b>${brl(o)}</b></div></div><form onsubmit="G.payCard(event,'${c.id}')" class="formgrid"><div class="field full"><label>Quanto vai pagar agora?</label><input name="amount" inputmode="decimal" value="${String(o.toFixed(2)).replace('.',',')}" required></div><div class="field full"><label>Data do pagamento</label><input name="date" type="date" value="${dueDate(c,m)}" required></div><div class="field full muted small">Se pagar menos, o restante continua em aberto automaticamente.</div><div class="field full formactions"><button class="btn" type="button" onclick="G.close()">Cancelar</button><button class="btn primary">Registrar pagamento</button></div></form></div></div>`};
  V.modalHandlers.cardplan=()=>{const c=by(S.cards,S.modal.id);if(!c)return'';const m=month(),o=open(c,m),due=dueDate(c,m);return `<div class="modalback" onclick="if(event.target===this)G.close()"><div class="modal"><div class="modalhead"><h2>Parcelar fatura · ${esc(c.name)}</h2><button class="close" onclick="G.close()">×</button></div><div class="invoicebrief"><div><span>Valor em aberto</span><b>${brl(o)}</b></div></div><form onsubmit="G.planCard(event,'${c.id}')" oninput="G.previewPlan()" class="formgrid"><div class="field"><label>Entrada</label><input name="entry" inputmode="decimal" value="0,00"></div><div class="field"><label>Entrada já paga?</label><select name="entry_paid"><option value="no">Não</option><option value="yes">Sim</option></select></div><div class="field"><label>Número de parcelas</label><input name="count" type="number" min="1" max="60" value="6"></div><div class="field"><label>Valor de cada parcela</label><input name="installment" inputmode="decimal" value="${String((o/6).toFixed(2)).replace('.',',')}"></div><div class="field full"><label>Primeira parcela</label><input name="first" type="date" value="${H.monthDate(due,1)}"></div><div id="planPreview" class="planpreview full">Total do acordo: ${brl(o)} · diferença: ${brl(0)}</div><div class="field full formactions"><button class="btn" type="button" onclick="G.close()">Cancelar</button><button class="btn primary">Salvar parcelamento</button></div></form></div></div>`};
  Object.assign(G,{
    cardFilter(id){S.cardFilter=S.cardFilter===id?null:id;render()},
    cardPurchaseChanged(id){const c=by(S.cards,id),date=document.querySelector('#purchaseDate')?.value||today(),due=document.querySelector('#purchaseDue'),owner=document.querySelector('#purchaseOwner');if(c&&due)due.value=inferredDue(c,date);if(owner)owner.textContent='Responsável: '+(c?pname(H.cardOwner(c)):'—')},
    async submitPurchaseV4(e){e.preventDefault();const f=new FormData(e.target),c=by(S.cards,String(f.get('card'))),count=Number(f.get('count')||1),amt=num(f.get('amount')),first=String(f.get('first')),category=f.get('subcategory')||f.get('category')||null,has=String(f.get('has_reimb'))==='yes',rv=num(f.get('reimb_amount'));if(!c)return;if(has&&!(rv>0))return toast('Informe o valor do reembolso.',true);await mutate(async()=>{await C.rpc('create_card_purchase',{p_credit_card_id:c.id,p_description:String(f.get('description')),p_total_amount:amt,p_purchase_date:String(f.get('date')),p_installments_count:count,p_first_due_date:first,p_category_id:category,p_reimbursable:has,p_notes:f.get('notes')||null});if(has){const base=Math.floor(rv*100/count)/100,rest=Math.round((rv-base*count)*100)/100;for(let i=0;i<count;i++){const value=i===count-1?base+rest:base;await createCardReimb(c,String(f.get('description')),value,H.monthDate(first,i))}}},'Compra no cartão salva')},
    async saveCardSettings(e,id){e.preventDefault();const f=new FormData(e.target),cur=S.household?.settings?.card_settings||{},next={...cur,[id]:{limit:num(f.get('limit')),closing_day:Number(f.get('closing')||1),due_day:Number(f.get('due')||10)}};await mutate(()=>H.saveSettings({card_settings:next}),'Cartão atualizado')},
    async payCard(e,id){e.preventDefault();const f=new FormData(e.target),c=by(S.cards,id),m=month(),pay=num(f.get('amount')),o=open(c,m),pid=H.cardOwner(c),acct=H.primaryAccount(pid),date=String(f.get('date'));if(!(pay>0)||pay>o+0.01)return toast('Informe um valor válido até o saldo em aberto.',true);if(!acct)return toast('Não encontrei a conta principal do responsável.',true);await mutate(async()=>{await clearOpen(c,m);await H.insertTx({household_id:S.hid,type:'card_payment',status:'paid',description:`Pagamento fatura ${c.name}`,responsible_person_id:pid,account_id:acct.id,competency_date:date,due_date:date,effective_date:date,planned_amount:pay,actual_amount:pay,notes:`${H.tag('cardpay',c.id,m)} Pagamento da fatura`,origin:'manual',created_by:S.session.user.id});await createOpen(c,m,Math.max(0,o-pay),dueDate(c,m))},pay>=o-0.01?'Fatura paga':'Pagamento parcial registrado; saldo restante continua em aberto')},
    previewPlan(){const form=document.querySelector('.modal form'),box=document.querySelector('#planPreview');if(!form||!box)return;const f=new FormData(form),entry=num(f.get('entry')),count=Number(f.get('count')||0),inst=num(f.get('installment')),total=entry+count*inst,c=by(S.cards,S.modal?.id),o=c?open(c,month()):0;box.textContent=`Total do acordo: ${brl(total)} · diferença sobre a fatura: ${brl(total-o)}`},
    async planCard(e,id){e.preventDefault();const f=new FormData(e.target),c=by(S.cards,id),m=month(),o=open(c,m),entry=num(f.get('entry')),entryPaid=String(f.get('entry_paid'))==='yes',count=Number(f.get('count')||0),inst=num(f.get('installment')),first=String(f.get('first')),pid=H.cardOwner(c),acct=H.primaryAccount(pid),planId=H.uuid();if(!c||!acct||count<1||inst<=0)return toast('Confira os dados do parcelamento.',true);const total=entry+count*inst;await mutate(async()=>{await clearOpen(c,m);const plans={...(S.household?.settings?.card_plans||{}),[`${c.id}:${m}`]:{plan_id:planId,original_open:o,entry,installments:count,installment_amount:inst,total,date:today(),first_due:first}};await H.saveSettings({card_plans:plans});if(entry>0)await H.insertTx({household_id:S.hid,type:'card_payment',status:entryPaid?'paid':'pending',description:`${c.name} — entrada do parcelamento`,responsible_person_id:pid,account_id:acct.id,competency_date:today(),due_date:today(),effective_date:entryPaid?today():null,planned_amount:entry,actual_amount:entryPaid?entry:null,notes:`${H.tag('cardplan',c.id,m,planId)} Entrada`,origin:'manual',created_by:S.session.user.id});for(let i=0;i<count;i++){const d=H.monthDate(first,i);await H.insertTx({household_id:S.hid,type:'card_payment',status:'pending',description:`${c.name} — parcela ${i+1}/${count}`,responsible_person_id:pid,account_id:acct.id,competency_date:d,due_date:d,planned_amount:inst,actual_amount:null,notes:`${H.tag('cardplan',c.id,m,planId)} Parcela ${i+1}/${count}`,origin:'manual',created_by:S.session.user.id})}},`Fatura parcelada em ${count}x ${brl(inst)}${entry>0?' com entrada de '+brl(entry):''}. Total ${brl(total)}`)}
  });
  render();
})();
